# Importa librerías requeridas

In [2]:
from datetime import date, timedelta
from pyspark.sql.types import *

# Calcula rango de fechas

## Desde una fecha predefinida como inicio hasta el final del año actual

In [4]:
today = date.today()

startDate = date(2000, 1, 1)   # start date
endDate = date(date.today().year, 8, 31)   # end date

delta = endDate - startDate       # as timedelta

dates = []

for i in range(delta.days + 1):
    day = startDate + timedelta(days=i)
    period = str(day.year)+'{:02d}'.format(day.month)
    dateRow = [day,period]
    dates.append(dateRow)

## Genera el esquema y datos en formato DataFrame

In [6]:
dateSchema = StructType([StructField("fecha", DateType()),StructField("periodo", StringType())])

In [7]:
dfDates = spark.createDataFrame(dates, schema = dateSchema)

## Escribe en tabla Hive las fechas

In [9]:
dfDates.write.mode("overwrite").saveAsTable("default.fechas")

In [10]:
%sql 
-- Consultar la nueva tabla de fechas
select * from default.fechas
limit 5

fecha,periodo
2018-01-27,201801
2018-01-28,201801
2018-01-29,201801
2018-01-30,201801
2018-01-31,201801